#Basic Config
spring.application.name=LawCase-Service
server.port=8012

#Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka

# Spring Data MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/LawCases
spring.data.mongodb.database=lawofficedb
spring.data.mongodb.auto-index-creation=true

# Optional: Logging for MongoDB queries
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO

#Open APi Config
# Include actuator endpoints (if you use Spring Boot Actuator)
springdoc.show-actuator=true
springdoc.api-docs.path=/api-docs

#Zipkin Config
spring.zipkin.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0

#Actuator + Prometheus
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted

#Resilinece4j Properties
resilience4j.circuitbreaker.instances.lawcase.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.lawcase.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.lawcase.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.lawcase.slidingWindowSize=10
resilience4j.circuitbreaker.instances.lawcase.failureRateThreshold=50
resilience4j.circuitbreaker.instances.lawcase.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.lawcase.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.lawcase.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=500ms
resilience4j.retry.configs.default.enableExponentialBackoff=true
resilience4j.retry.configs.default.exponentialBackoffMultiplier=2
resilience4j.retry.instances.lawcase.baseConfig=default

resilience4j.ratelimiter.configs.default.limitForPeriod=5
resilience4j.ratelimiter.configs.default.limitRefreshPeriod=1s
resilience4j.ratelimiter.configs.default.timeoutDuration=0
resilience4j.ratelimiter.instances.lawcase.baseConfig=default