#Basic Config
spring.application.name=LawCase-Service
server.port=8012

#Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka

# Spring Data MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/LawCases
spring.data.mongodb.database=lawofficedb
spring.data.mongodb.auto-index-creation=true

# Optional: Logging for MongoDB queries
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO

#Open APi Config
# Include actuator endpoints (if you use Spring Boot Actuator)
springdoc.show-actuator=true
springdoc.api-docs.path=/api-docs

#Zipkin Config
spring.zipkin.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
